# upload root path
upload:
  root.path: /data/file
  temporary.path: /temporary
  real.path: /real
  #1주일 주기 임시파일생성 경로 - 프로세스내에서 1회성 임시파일 생성 후 파일 생성일자가 1일(24시간 or 클라이언트가 다운로드 완료까지 넉넉한 시간(10분?))이 초과하면 반드시 삭제처리한다. - NexacroFileResult 에서 생성자 파라미터가 File이라 파일생성없이는 사용이 불가하므로 해당 경로를 활용 한다.
  pending.delete.weekly.path: /pending/delete

# synapsoft viewer solution
sol.sn3hcv:
  home: /opt/synap/sn3hcv/
  sn3hcv: /opt/synap/sn3hcv/sn3hcv_exe
  template: /opt/synap/sn3hcv/template
  modules: /opt/synap/sn3hcv/modules
# synapsoft viewer generation
  web.root: /opt/tomcat/apache-tomcat-9.0.80/webapps/irs/WEB-INF/classes/static/sn3hcv
  rs.root: /sn3hcv

# juso api address
juso:
  api-key: devU01TX0FVVEgyMDI0MDExODExMDIyODExNDQ0NTM=
  addr-link-api: https://business.juso.go.kr/addrlink/addrLinkApi.do
  addr-link-api-domian: https://business.juso.go.kr
  
# sms api address
sms:
  project-name: irs-dev-sms-api
  service-url: https://sens.apigw.gov-ntruss.com
  service-id: ncp-gov:sms:kr:1002933503:irs-dev-sms-api
  access-key: D4FD5A7868874CC7D19A
  secret-key: FDF8604996440380A3E44E092156D7D41BDFC684
  from-tel: "0437147522"
   
# examples
web.example.prop: prop-dev