### 환경 공통
---

##########################################################################################
--- # local 전용 설정
spring:
  config:
    activate:
      on-profile: "local"
server:
  port: 28080
  servlet:
    context-path: /irs
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
##########################################################################################
--- # common
spring:
  application.name: gov-me-irs-${spring.profiles.active}
  config:
    import:
      - classpath:config/core/common/core.yml
      - classpath:config/${spring.profiles.active}/web-ext.yml
      - classpath:config/${spring.profiles.active}/raon-k.yml
      - classpath:config/${spring.profiles.active}/jwt.yml
      - classpath:config/${spring.profiles.active}/safedb.yml
      - classpath:config/error/errorcode.properties
  servlet:
    multipart:
      max-file-size: 50MB
      # 50MB x 30
      max-request-size: 1500MB
      
##########################################################################################
--- # yml - properties
spring:
  messages:
    basename: i18n/message/messages
    encoding: UTF-8
    cache-duration: 30
    always-use-message-format: true
    use-code-as-default-message: true
    fallback-to-system-locale: false

##########################################################################################
--- # Jpa
spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none  # 스키마 유효성 검사 옵션
      use-new-id-generator-mappings: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true  # 실행되는 SQL 출력 여부 - JPA전용
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

##########################################################################################
--- # jackson
# spring.jackson.serialization.fail-on-empty-beans 속성을 true로 설정하면, Jackson은 빈 객체를 직렬화할 때 JsonMappingException 예외를 발생시킵니다.
spring:
  jackson:
    serialization:
      fail-on-empty-beans: false

##########################################################################################
--- # mybatis - dbms
mybatis:
  configuration:
    multiple-result-sets-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500
  type-aliases-package: gov.me.irs.common.util, gov.me.irs.**.vo
  mapper-locations: classpath:mappers/**/*.xml

############################################
--- # Logging
logging:
  config: classpath:config/core/${spring.profiles.active}/log4j2.xml

##########################################################################################
--- # yml - cache : 캐싱방지
spring:
  web:
    resources:
      cache:
        cachecontrol:
          no-cache: true
          no-store: true
