
##########################################################################################
--- # profiles
spring.profiles.active: local

##########################################################################################
--- # common
server:
  port: 80
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
### 환경 공통
---
spring:
  application.name: bak-me-irs-${spring.profiles.active}
  config:
    import:
      - classpath:config/${spring.profiles.active}/web-ext.yml
      - classpath:config/${spring.profiles.active}/jwt.yml
      - classpath:config/error/errorcode.properties
    
##########################################################################################
--- # yml - properties
spring:
  messages:
    basename: i18n/message/messages
    encoding: UTF-8
    cache-duration: 30
    always-use-message-format: true
    use-code-as-default-message: true
    fallback-to-system-locale: false

##########################################################################################
--- # Jpa
spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none  # 스키마 유효성 검사 옵션
      use-new-id-generator-mappings: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true  # 실행되는 SQL 출력 여부 - JPA전용
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

##########################################################################################
--- # jackson
# spring.jackson.serialization.fail-on-empty-beans 속성을 true로 설정하면, Jackson은 빈 객체를 직렬화할 때 JsonMappingException 예외를 발생시킵니다.
spring:
  jackson:
    serialization:
      fail-on-empty-beans: false

##########################################################################################
--- # mybatis - dbms
mybatis:
  configuration:
    multiple-result-sets-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500
  type-aliases-package: gov.me.irs.common.util, gov.me.irs.**.vo
  mapper-locations: classpath:mappers/**/*.xml
  
############################################
--- # Data Source
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ENC(Sb2I3TheMFFLL6gNQhGlb13vji7bX7vJFjjcn43ttHySRrZLywLpKxF4pKbX864wuHVMDDKIPkFySsADJxY1gg==)
    username: ENC(M844TzV46J5wj5Ew/r4ic/3MR1nVKzZ4)
    password: ENC(+cbQdTVbVm7yVC7UWfy+WoPQ9S11OF0P)

############################################
--- # Logging
logging:
  config: classpath:config/core/${spring.profiles.active}/log4j2.xml

##########################################################################################
--- # jasypt
jasypt.encryptor.password: 1234567890QWERTYUIOPASDFGHJKLZXCVBNM30987654321

##########################################################################################
--- # yml - cache : 캐싱방지
spring:
  web:
    resources:
      cache:
        cachecontrol:
          no-cache: true
          no-store: true
