############################################
--- # Data Source
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ENC(3j1QNdwp8YDDKIerIRMD40I0NzaBA8gEqrBNSwBU952fucn+wsZjTv7+M8gqnx+cXopKSghKMixxtEjhoC7t+g==)
    username: ENC(0EsFFMcbg5J6blwaKygShA==)
    password: ENC(AIx6awkAbiAZyPaRapcmYAzx90iZjzrk)
    hikari:
      pool-name: irsHikari
      # 유휴 connection - 5개
      minimum-idle: 5
      # connection 최대 시간 - 20초
      connection-timeout: 20000
      # pool size - 기본값 10
      maximum-pool-size: 10
      # connection 최대 유지시간, 수명, 반환시간 - 10분
      max-lifetime: 600000
      # connection 유효성 검사 - 3초
      validation-timeout: 3000
      connection-init-sql: SELECT 1

##########################################################################################
--- # jasypt
jasypt.encryptor.password: 1234567890QWERTYUIOPASDFGHJKLZXCVBNM30987654321
