############################################
--- # Data Source
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    # jdbc:log4jdbc:postgresql://127.0.0.1:15432/postgres
    url: ENC(mXC8GElHIxRrSxv/1vk9Nl61oXiRa/fWywB1WQdxGcLzSK4tZCfVKMAZWBLYFncfeIqhLunBXn7XXVZbi/typw==)
    # username : girirs
    # username: ENC(5rXPK8Q2mzZXv8TFCm79VA==)
    # username : devgirirs
    username: ENC(XklR2sthimLQStiQ6EfQD69bBPvRFNnr)
    password: ENC(oWBsc9H2AiE9ONt0bB3jHkBxaaFNX+AC)
    hikari:
      pool-name: irsHikari
      # 유휴 connection - 5개
      minimum-idle: 5
      # connection 최대 시간 - 20초
      connection-timeout: 20000
      # pool size - 기본값 10
      maximum-pool-size: 10
      # connection 최대 유지시간, 수명, 반환시간 - 10분
      max-lifetime: 600000
      # connection 유효성 검사 - 3초
      validation-timeout: 3000
      connection-init-sql: SELECT 1

##########################################################################################
--- # jasypt
jasypt.encryptor.password: 1234567890QWERTYUIOPASDFGHJKLZXCVBNM30987654321
