
DROP TABLE irs_user.FILE_DTL;
DROP TABLE irs_user.FILE_GROUP_BSC;

/* ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ */
/* 파일그룹기본*/
/* ▶ 파일 관리 */
/* 파일그룹기본 */
/* ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ */
CREATE TABLE irs_user.FILE_GROUP_BSC (
	FILE_GROUP_SN INTEGER NOT NULL,
	FILE_TYPE_CL_CD VARCHAR(7) NOT NULL,
	MENU_ID VARCHAR(20) NOT NULL,
	DEL_YN CHAR(1) DEFAULT 'N' NOT NULL,
	RGTR_ID VARCHAR(20) DEFAULT 'SYSTEM',
	REG_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	MDFR_ID VARCHAR(20) DEFAULT 'SYSTEM',
	MDFCN_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	
	CONSTRAINT PK_FILE_GROUP_BSC PRIMARY KEY (FILE_GROUP_SN)
);

COMMENT ON TABLE irs_user.FILE_GROUP_BSC IS '파일그룹기본';
COMMENT ON COLUMN irs_user.FILE_GROUP_BSC.FILE_GROUP_SN IS '파일그룹일련번호';
COMMENT ON COLUMN irs_user.FILE_GROUP_BSC.FILE_TYPE_CL_CD IS '파일유형구분코드';
COMMENT ON COLUMN irs_user.FILE_GROUP_BSC.MENU_ID IS '메뉴ID';
COMMENT ON COLUMN irs_user.FILE_GROUP_BSC.DEL_YN IS '삭제여부';
COMMENT ON COLUMN irs_user.FILE_GROUP_BSC.RGTR_ID IS '등록ID';
COMMENT ON COLUMN irs_user.FILE_GROUP_BSC.REG_DT IS '등록일시';
COMMENT ON COLUMN irs_user.FILE_GROUP_BSC.MDFR_ID IS '수정ID';
COMMENT ON COLUMN irs_user.FILE_GROUP_BSC.MDFCN_DT IS '수정일시';


/* ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ */
/* 파일상세*/
/* ▶ 파일 관리 */
/* 파일상세 목록 */
/* ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ */
CREATE TABLE irs_user.FILE_DTL (
	FILE_GROUP_SN INTEGER NOT NULL,
	FILE_DTL_SN INTEGER NOT NULL,
	ORGNL_FILE_NM VARCHAR(256) NOT NULL,
	FILE_PATH_NM VARCHAR(200) NOT NULL,
	FILE_NM VARCHAR(256) NOT NULL,
	FILE_SZ INTEGER NOT NULL,
	FILE_EXTN_NM VARCHAR(20) NOT NULL,
	DWNLD_CNT INTEGER NOT NULL,
	DEL_YN CHAR(1) DEFAULT 'N' NOT NULL,
	RGTR_ID VARCHAR(20) DEFAULT 'SYSTEM',
	REG_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	MDFR_ID VARCHAR(20) DEFAULT 'SYSTEM',
	MDFCN_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	
	CONSTRAINT PK_FILE_DTL PRIMARY KEY (FILE_GROUP_SN, FILE_DTL_SN)
);



COMMENT ON TABLE irs_user.FILE_DTL IS '파일상세';
COMMENT ON COLUMN irs_user.FILE_DTL.FILE_GROUP_SN IS '파일그룹일련번호';
COMMENT ON COLUMN irs_user.FILE_DTL.FILE_DTL_SN IS '파일상세일련번호';
COMMENT ON COLUMN irs_user.FILE_DTL.ORGNL_FILE_NM IS '원본파일명';
COMMENT ON COLUMN irs_user.FILE_DTL.FILE_PATH_NM IS '파일경로명';
COMMENT ON COLUMN irs_user.FILE_DTL.FILE_NM IS '파일명';
COMMENT ON COLUMN irs_user.FILE_DTL.FILE_SZ IS '파일크기';
COMMENT ON COLUMN irs_user.FILE_DTL.FILE_EXTN_NM IS '파일확장자명';
COMMENT ON COLUMN irs_user.FILE_DTL.DWNLD_CNT IS '다운로드수';
COMMENT ON COLUMN irs_user.FILE_DTL.DEL_YN IS '삭제여부';
COMMENT ON COLUMN irs_user.FILE_DTL.RGTR_ID IS '등록ID';
COMMENT ON COLUMN irs_user.FILE_DTL.REG_DT IS '등록일시';
COMMENT ON COLUMN irs_user.FILE_DTL.MDFR_ID IS '수정ID';
COMMENT ON COLUMN irs_user.FILE_DTL.MDFCN_DT IS '수정일시';





