# upload root path
core:
  holiday:
    solar:
      - "0101"
      - "0301"
      - "0505"
      - "0606"
      - "0815"
      - "1003"
      - "1009"
      - "1225"
    lunar:
      - "0101"
      - "0102"
      - "0408"
      - "0814"
      - "0815"
      - "0816"